version: "3.8"

services:
  # Node.js application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/todo-api
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev

  # MongoDB service
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
